# Generated by Django 4.0.4 on 2022-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callinfo', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(unique=True),
        ),
    ]
