# Generated by Django 4.0.4 on 2022-09-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callinfo', '0006_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('spam', models.CharField(default='No', editable=False, max_length=3)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='globalusers', to='callinfo.user')),
            ],
        ),
    ]
