# Generated by Django 4.0.4 on 2022-09-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callinfo', '0007_globalusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalusers',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='globalusers', to='callinfo.user'),
        ),
    ]
