# Generated by Django 4.0.4 on 2022-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callinfo', '0008_alter_globalusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalusers',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
